use crate::{models::SearchResult, storage};
use std::{fs, io::{self, Cursor}, path::{Path, PathBuf}, process::Command};
use tauri::AppHandle;

pub fn dependency_paths(app: &AppHandle) -> Result<(PathBuf,PathBuf,PathBuf),String> { let d=storage::tools_dir(app)?; Ok((d.join("yt-dlp.exe"),d.join("ffmpeg.exe"),d.join("ffprobe.exe"))) }
pub fn find_tool(app:&AppHandle,name:&str)->Result<Option<PathBuf>,String>{let (y,f,p)=dependency_paths(app)?;let own=match name{"ytdlp"=>y,"ffmpeg"=>f,"ffprobe"=>p,_=>return Err("Unknown dependency".into())};if own.exists(){return Ok(Some(own));}let output=Command::new("where.exe").arg(if name=="ytdlp"{"yt-dlp.exe"}else if name=="ffmpeg"{"ffmpeg.exe"}else{"ffprobe.exe"}).output();if let Ok(out)=output{if out.status.success(){if let Some(line)=String::from_utf8_lossy(&out.stdout).lines().next(){let p=PathBuf::from(line.trim());if p.exists(){return Ok(Some(p));}}}}Ok(None)}

pub fn install(app:&AppHandle,name:&str)->Result<(),String>{match name{"ytdlp"=>{let bytes=download("https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe")?;if bytes.len()<1_000_000{return Err("The yt-dlp download was incomplete.".into());}let (path,_,_)=dependency_paths(app)?;fs::write(path,bytes).map_err(|e|e.to_string())},"ffmpeg"=>install_ffmpeg(app),_=>Err("Unknown dependency".into())}}
fn download(url:&str)->Result<Vec<u8>,String>{let response=reqwest::blocking::Client::builder().user_agent("EclipsePhonePlayer/1.0").build().map_err(|e|e.to_string())?.get(url).send().map_err(|e|e.to_string())?.error_for_status().map_err(|e|e.to_string())?;Ok(response.bytes().map_err(|e|e.to_string())?.to_vec())}
fn install_ffmpeg(app:&AppHandle)->Result<(),String>{let bytes=download("https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip")?;let mut archive=zip::ZipArchive::new(Cursor::new(bytes)).map_err(|e|e.to_string())?;let tools=storage::tools_dir(app)?;for i in 0..archive.len(){let mut file=archive.by_index(i).map_err(|e|e.to_string())?;let name=Path::new(file.name()).file_name().and_then(|x|x.to_str()).unwrap_or("");if name.eq_ignore_ascii_case("ffmpeg.exe")||name.eq_ignore_ascii_case("ffprobe.exe"){let mut out=fs::File::create(tools.join(name)).map_err(|e|e.to_string())?;io::copy(&mut file,&mut out).map_err(|e|e.to_string())?;}}if !tools.join("ffmpeg.exe").exists(){return Err("FFmpeg was not found inside the downloaded package.".into());}Ok(())}

pub fn search(app:&AppHandle,query:&str)->Result<Vec<SearchResult>,String>{let exe=find_tool(app,"ytdlp")?.ok_or("yt-dlp is not installed")?;let template="%(title)s\t%(uploader)s\t%(duration_string)s\t%(webpage_url)s\t%(thumbnail)s";let output=Command::new(exe).args([format!("ytsearch15:{query}"),"--flat-playlist".into(),"--no-warnings".into(),"--encoding".into(),"utf-8".into(),"--print".into(),template.into()]).output().map_err(|e|e.to_string())?;if !output.status.success(){return Err(String::from_utf8_lossy(&output.stderr).trim().to_string());}let mut results=Vec::new();for line in String::from_utf8_lossy(&output.stdout).lines(){let f:Vec<_>=line.split('\t').collect();if f.len()<4{continue;}results.push(SearchResult{title:f[0].into(),channel:f[1].into(),length:if f[2]=="NA"{"—".into()}else{f[2].into()},url:f[3].into(),thumbnail:f.get(4).map(|x|x.to_string()).filter(|x|x!="NA")});}Ok(results)}

pub fn download_media(app:&AppHandle,url:&str,kind:&str)->Result<String,String>{let ytdlp=find_tool(app,"ytdlp")?.ok_or("yt-dlp is not installed")?;let settings=storage::load_settings(app)?;let root=if settings.download_folder.trim().is_empty(){storage::data_dir(app)?.join("Downloads")}else{PathBuf::from(settings.download_folder)};let target=root.join(if kind=="audio"{"Downloaded Audio"}else{"Downloaded Video"});fs::create_dir_all(&target).map_err(|e|e.to_string())?;let mut cmd=Command::new(ytdlp);cmd.args(["--no-playlist","--windows-filenames","-P"]).arg(&target).args(["-o","%(title).180B [%(id)s].%(ext)s"]);if kind=="audio"{let ffmpeg=find_tool(app,"ffmpeg")?.ok_or("FFmpeg is required for MP3 downloads")?;cmd.args(["-f","bestaudio","--extract-audio","--audio-format","mp3","--audio-quality","0","--ffmpeg-location"]).arg(ffmpeg);}else if let Some(ffmpeg)=find_tool(app,"ffmpeg")?{cmd.args(["-f","bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b","--merge-output-format","mp4","--ffmpeg-location"]).arg(ffmpeg);}else{cmd.args(["-f","b[ext=mp4]/b"]);}let status=cmd.arg(url).status().map_err(|e|e.to_string())?;if !status.success(){return Err(format!("yt-dlp exited with code {:?}",status.code()));}Ok(target.to_string_lossy().to_string())}
